create table public.songs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  song_path text null,
  image_path text null,
  author text null,
  user_id uuid null,
  constraint songs_pkey primary key (id),
  constraint songs_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create policy "Enable read access for all users"
on "public"."songs"
as PERMISSIVE
for SELECT
to public
using (
    true
);

create policy "Enable insert for authenticated users only"
on "public"."songs"
as PERMISSIVE
for INSERT
to authenticated
with check (
    true
);